# Generated by Django 4.2.5 on 2023-10-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apiapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=1000)),
                ('task_desc', models.CharField(max_length=10000)),
            ],
        ),
    ]
